# Numpy Part-2

In [1]:
import numpy as np

In [3]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 및 axis

In [5]:
# 모든 요소들의 합
a.sum()

78

In [6]:
# 열의 합(세로)
a.sum(axis=0)

array([15, 18, 21, 24])

In [9]:
# 행의 합(가로)
a.sum(axis=1)

array([10, 26, 42])

In [10]:
np.sum(a[0])

10

In [11]:
np.sum(a[1])

26

In [13]:
a.min(axis=0)

array([1, 2, 3, 4])

In [14]:
a.max(axis=1)

array([ 4,  8, 12])

In [15]:
a.mean()

6.5

In [16]:
a.mean(axis=0), a.mean(axis=1)

(array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))

- sorting

In [17]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [18]:
np.sort(b) # axis = 1 , ascending order

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [19]:
np.sort(b,axis=0)

array([[ 1,  3,  1,  7],
       [ 2,  5,  5,  9],
       [ 4, 12, 11, 14]])

In [20]:
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [21]:
b.sort()

In [22]:
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [24]:
b.sort(axis=0)
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [26]:
# 내림차순
c=np.array([42,38,12,25])
np.sort(c)[::-1]

array([42, 38, 25, 12])

In [28]:
np.argsort(c) # 오름차순으로 정렬하고 인덱스값을 표시

array([2, 3, 1, 0], dtype=int64)

In [29]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

In [31]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

- Mathematical Functions



In [36]:
# 지수 함수: exp, expml, exp2, log, log10, loglp, log2, power, sqrt 

# 삼각 함수: sin, cos, tan, arcsin, arccos, arctan 
# Hyperbolic: sinh, cosh, tanh, arcsinh, arccosh, arctanh

In [32]:
# sigmoid 함수
def sigmoid(x):
    return 1. / (1+np.exp(-x))

In [33]:
X = np.array([-10,0,10])
sigmoid(X)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

- Transpose(전치)

In [37]:
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [38]:
b.T

array([[ 1,  1,  3],
       [ 2,  4,  9],
       [ 5,  5, 11],
       [ 7, 12, 14]])

- concatenate , vstack , hstack

In [40]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [41]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [43]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [46]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### 5. Array operation

- 4칙연산

In [48]:
a

array([[1, 2],
       [3, 4]])

In [49]:
a+a

array([[2, 4],
       [6, 8]])

In [50]:
a-a

array([[0, 0],
       [0, 0]])

In [51]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [52]:
a/a

array([[1., 1.],
       [1., 1.]])

- Broadcastion

In [53]:
a+1


array([[2, 3],
       [4, 5]])

In [54]:
a+3


array([[4, 5],
       [6, 7]])

- Dot product

In [55]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)

In [56]:
np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [57]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [58]:
np.dot(np.array([1,2,3]), np.array([4,5,6]))

32

### 6. Comparison

- all & any

In [61]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [65]:
np.any(a>5) # 하나라도 True 면 True

True

In [66]:
np.all(a>5)  # 모두가 True 라야 True

False

In [67]:
b = np.logical_and(a>3,a<7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [68]:
np.logical_or(a > 7 , a<3)


array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax , argmin

In [72]:
a.argmax(), np.argmax(a)

(9, 9)

In [73]:
a.argmin(), np.argmin(a)

(0, 0)

### 7. Booleam & Fancy indexing

In [74]:
# array a 에서 값이 6 이상인 것만 가져오기 - filtering
a[a>=6]

array([6, 7, 8, 9])

In [75]:
a>=6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [76]:
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [77]:
a[b]

array([4, 5, 6])

- Fancy indexing

In [78]:
a= np.array([2,4,6,8])
b= np.array([0,0,1,3,2,1])
a[b]

array([2, 2, 4, 8, 6, 4])

### 8. 기술 통계

In [79]:
a = np.random.randn(10)
a

array([-1.00432505, -0.77233572, -0.43946099,  0.30593569, -0.02040241,
       -0.37950678, -0.43736531, -0.73681329,  1.00773403,  0.98952543])

In [80]:
# 평균
np.mean(a), a.mean()

(-0.14870143846071535, -0.14870143846071535)

In [81]:
# 표준편차(standard deviation)
np.std(a), a.std()

(0.6740982889088848, 0.6740982889088848)

In [82]:
#최소 최대
a.min(), a.max()

(-1.0043250504371963, 1.0077340265660826)

In [83]:
# 4분위수
np.percentile(a,25), np.percentile(a,50), np.percentile(a,75)

(-0.6624752139898537, -0.4084360414649811, 0.22435116873287014)

In [84]:
# 중앙값
np.median(a)

-0.4084360414649811

In [85]:
a= np.random.randint(0,3,100)
a

array([2, 1, 2, 1, 2, 1, 1, 0, 1, 1, 1, 2, 2, 0, 2, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 2, 1, 0, 1, 0, 2, 1, 0, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 1, 2,
       1, 0, 2, 0, 2, 2, 2, 0, 0, 1, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 2,
       1, 1, 2, 1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 2, 2, 1, 2, 1, 0, 0, 0, 0,
       2, 1, 2, 1, 2, 2, 1, 0, 1, 0, 2, 2])

In [86]:
# 0,1,2 의 갯수
np.unique(a, return_counts=True)

(array([0, 1, 2]), array([33, 37, 30], dtype=int64))