### 연습문제 1
<pre>
넘파이를 사용하여 다음과 같은 행렬을 만드시오. 
10 20 30 40 
50 60 70 80
</pre>

In [1]:
import numpy as np

In [7]:
a= np.arange(10,81,10).reshape(2,4)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 연습문제 2
<pre>
다음 행렬과 같은 행렬이 있다. 
m = np.array([  [ 0, 1, 2, 3, 4], 
                [ 5, 6, 7, 8, 9], 
                [10, 11, 12, 13, 14]])
1)이 행렬에서 값 7 을 인덱싱한다.
2)이 행렬에서 값 14 을 인덱싱한다.
3)이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4)이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5)이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
</pre>

In [58]:
m = np.array([  [ 0, 1, 2, 3, 4], 
                [ 5, 6, 7, 8, 9], 
                [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
# 1)이 행렬에서 값 7 을 인덱싱한다.
m[1][2]

7

In [13]:
# 2)이 행렬에서 값 14 을 인덱싱한다.
m[2][4]

14

In [19]:
# 3)이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1:2,1:3]

array([[6, 7]])

In [20]:
# 4)이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:, 2:3]

array([[ 7],
       [12]])

In [21]:
# 5)이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:2,3:]

array([[3, 4],
       [8, 9]])

### 연습문제 3
<pre>
3.2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
1)이 배열에서 3의 배수를 찾아라.
2)이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3)이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
</pre>

In [61]:
f= m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
# 1)이 배열에서 3의 배수를 찾아라.
f1 = f[f%3==0]
f1

array([ 0,  3,  6,  9, 12])

In [65]:
# 2)이 배열에서 4로 나누면 1이 남는 수를 찾아라.
f2 = f[f%4==1]
f2

array([ 1,  5,  9, 13])

In [70]:
# 3)이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
f3 = f1[f1%4==1]
f3

array([9])

### 연습문제 4
<pre>
4.값을 직접 입력하지 말고 우측의 행렬을 만드시오.

2, 1, 0, 0, 0 
3, 2, 1, 0, 0
0, 3, 2, 1, 0 
0, 0, 3, 2, 1 
0, 0, 0, 3, 2
</pre>

In [86]:
np.eye(N=5 , M=5,k=-1, dtype=int)*3+np.eye(N=5 , M=5, dtype=int)*2+np.eye(N=5 , M=5,k=1, dtype=int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

In [74]:
np.eye(3,5,k=0,dtype=int)+ np.eye(3,5,k=2, dtype=int)

array([[1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1]])

### 연습문제 5
<pre>
0에서 10까지 랜덤 실수값으로 이루어진 
5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 
다음과 같은 값을 구하시오.
1)전체의 최댓값
2)각 행의 합
3)각 행의 최댓값
4)각 열의 평균
5)각 열의 최솟값
</pre>

In [94]:
import random
b = np.random.randint(0,11,30).reshape(5,6)
b

array([[ 1,  7,  7, 10,  1,  9],
       [ 8,  0,  5,  2,  6,  8],
       [ 8,  3,  5,  9,  4,  6],
       [ 9,  4,  4,  0,  9,  6],
       [ 5,  1,  7,  8,  9,  5]])

In [95]:
# 1)전체의 최댓값
b.max()


10

In [96]:
# 2)각 행의 합
b.sum(axis=1)

array([35, 29, 35, 32, 35])

In [97]:
# 3)각 행의 최댓값
b.max(axis=1)

array([10,  8,  9,  9,  9])

In [99]:
# 4)각 열의 평균
b.mean(axis=0)

array([6.2, 3. , 5.6, 5.8, 5.8, 6.8])

In [100]:
# 5)각 열의 최솟값
b.min(axis=0)

array([1, 0, 4, 0, 1, 5])

### 연습문제 6
<pre>
6.다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 
세번째 행에 수학 성적을 적은 배열이다. 
영어 성적을 기준으로 각 열(column)을 재정렬하시오.
array([ [ 1, 2, 3, 4], 
        [ 46, 99, 100, 71], 
        [ 81, 59, 90, 100]])
</pre>

In [187]:
c = np.array([1,2,3,4,  46, 99, 100, 71,  81, 59, 90, 100], dtype=np.int32).reshape(3,4)
c

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [207]:
c1 = np.array([ 1, 2, 3, 4])
c2 = np.array([ 46, 99, 100, 71])
c3 = np.array([ 81, 59, 90, 100])

print(c1)
print(c2)
print(c3)

[1 2 3 4]
[ 46  99 100  71]
[ 81  59  90 100]


In [208]:
i = c3.argsort()
i


array([1, 0, 2, 3], dtype=int64)

In [212]:
i = np.argsort(c3)
c1 = c1[i]
c2 = c2[i]
c3 = c3[i]
np.vstack((c1,c2,c3))

array([[  2,   1,   3,   4],
       [ 99,  46, 100,  71],
       [ 59,  81,  90, 100]])

### 연습문제 7
<pre>
7.주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.
</pre>

In [215]:
np.random.randint(1,7,100).mean()

3.77

### 연습문제 8
<pre>
8.가격이 10,000원인 주식이 있다. 
이 주식의 일간 수익률(%)은 기댓값이 0%이고 
표준편차가 1%인 표준 정규 분포를 따른다고 하자. 
250일 동안의 주가를 무작위로 생성하시오.
</pre>

In [279]:
e = np.random.randn(250)*100 +10000
e

array([ 9937.74792934,  9738.41560411,  9857.93395297,  9915.10790338,
       10012.01654047,  9889.48414108, 10072.42973813,  9933.69677556,
        9794.55126113,  9933.5624961 , 10155.33994878,  9959.15650312,
        9841.62732519, 10205.96076725,  9841.59013169,  9895.69518056,
       10073.64202572, 10080.40221215, 10025.44449336, 10157.32900613,
       10009.74060539, 10049.10552923,  9943.37573902, 10060.57568761,
        9900.6748033 ,  9893.15795818,  9950.68944543, 10036.37519449,
        9964.49738292, 10034.12902567,  9776.67169311,  9999.63481631,
        9931.32999732,  9993.48595028,  9948.77735839, 10046.80206642,
       10169.84224222,  9987.97511084,  9993.33457867, 10111.74320336,
       10004.01585929,  9990.13881943, 10194.35816023,  9901.96655292,
        9921.12600416, 10121.79803218, 10015.38086773, 10225.79934211,
       10161.7071877 , 10125.32491292,  9995.00401154,  9891.60115914,
        9957.16229546,  9980.75594569, 10017.75250725, 10138.26970125,
      